name: dzero
description: Desarrollo de una aplicacición Movil para el curso de taller de proyectos.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  go_router: ^6.5.2
  flutter_riverpod: ^2.3.4
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.4.0
  cloudinary_public: ^0.13.0
  firebase_database: ^10.1.1
  flutter_dotenv: ^5.0.2
  awesome_circular_chart: ^1.0.0
  animate_do: ^3.0.2
  formz: ^0.6.0
  uuid: ^3.0.7
  url_launcher: ^6.1.11
  google_fonts: ^4.0.4
  image_cropper: ^2.0.3
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/icons/logo-1.png'
  min_sdk_version: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/loaders/
    - .env
